### ISSUE TITLE
Ignored my issue

### ISSUE THREAD

**Issue by proyb6** [kostya/crystal-benchmarks-game#6]
I'm curious if you are planning to write V benchmarks game, I have seen your post in Vlang's repo.

**Comment by kostya** [comment]
maybe if  i have time

**Comment by kostya** [comment]
i add some benchmarks of V, here: https://github.com/kostya/benchmarks

**Comment by proyb6** [comment]
Appreciate for the benchmark on V, this help to assess my decision, Kostya!

For future readers on comparing V vs Go. Over certain business requirements, Go is a better choice for battle-tested and productive.
